app/models.py
from flask_sqlalchemy import SQLAlchemy
from datetime import date
db = SQLAlchemy()


class Authors(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    lastname = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(60), nullable=False)
    createdat = db.Column(db.Date, nullable=False, default=date.today)
    book = db.relationship('Books', backref='authors', lazy=True)

    def __repr__(self):
        return f'{self.name} {self.lastname}'


class Books(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    pub_date = db.Column(db.Date)
    createdat = db.Column(db.Date, nullable=False, default=date.today)
    autor_id = db.Column(db.Integer, db.ForeignKey('authors.id'), nullable=False)
    author = db.relationship('Authors', backref=db.backref('books', lazy=True))

    def __repr__(self):
        return f'{self.title}'

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, SelectField, DateField
from wtforms.widgets import CheckboxInput
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField('Nombre de Usuario', validators=[DataRequired()])
    password = PasswordField('Contrasenia', validators=[DataRequired()])
    submit = SubmitField('Enviar')


class AuthorForm(FlaskForm):
    name = StringField('Nombre', validators=[DataRequired()])
    lastname = StringField('Apellidos', validators=[DataRequired()])
    email = StringField('Email')
    submit = SubmitField('Aceptar')


class BookForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    authors = SelectField('Autor', coerce=int, validators=[DataRequired()])
    pub_date = DateField('Publication Date', format='%Y-%m-%d', validators=[DataRequired()])
    submit = SubmitField('Aceptar')

app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from .config import Config
from .auth import auth
from .author import author
from .book import book
from .models import db

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    app.register_blueprint(auth)
    app.register_blueprint(author)
    app.register_blueprint(book)
    db.init_app(app)
    Migrate(app, db, directory='./migrations')
    return app

app/author/__init__.py
from flask import Blueprint

author = Blueprint('author', __name__, url_prefix='/author')

from . import views

app/author/views.py
from flask import render_template, url_for, flash, redirect
from . import author
from ..models import db
from ..forms import AuthorForm
from ..models import Authors


@author.route('/list')
def list_authors():
    authors = Authors.query.all()
    context = {
        'authors': authors
    }
    return render_template('author/list.html', **context)


@author.route('/add', methods=['GET', 'POST'])
def add_author():
    form = AuthorForm()
    context = {
        'title': "Agregar",
        'form': form
    }
    if form.validate_on_submit():
        author = Authors(
            name=form.name.data,
            lastname=form.lastname.data,
            email=form.email.data
        )
        db.session.add(author)
        db.session.commit()
        flash('Author registrado con éxito!', 'success')
        return redirect(url_for('author.list_authors'))
    return render_template('author/form.html', **context)


@author.route('/edit/<int:author_id>', methods=['GET', 'POST'])
def edit_author(author_id):
    author = Authors.query.get_or_404(author_id)
    form = AuthorForm(obj=author)
    context = {
        'title': "Editar",
        'form': form,
        'author': author
    }
    if form.validate_on_submit():
        author.name=form.name.data,
        author.lastname=form.lastname.data,
        author.email=form.email.data
        db.session.commit()
        flash('Author editado con éxito!', 'success')
        return redirect(url_for('author.list_authors'))
    return render_template('author/form.html', **context)


@author.route('/delete/<int:author_id>', methods=['GET', 'POST'])
def delete_author(author_id):
    author = Authors.query.get_or_404(author_id)
    form = AuthorForm(obj=author)
    context = {
        'title': 'Eliminar',
        'form': form,
        'author': author
    }
    if form.validate_on_submit():
        db.session.delete(author)
        db.session.commit()
        flash('Author Eliminado con éxito!', 'success')
        return redirect(url_for('author.list_authors'))
    return render_template('author/form.html', **context)

app/book/__init__.py
from flask import Blueprint

book = Blueprint('book', __name__, url_prefix='/book')

from . import views

app/book/views.py
from flask import render_template, url_for, flash, session, redirect
from . import book
from ..models import db
from ..models import Authors
from ..models import Books
from ..forms import BookForm


@book.route('/list')
def list_books():
    books = Books.query.all()
    context = {
        'books': books
    }
    return render_template('book/list.html', **context)


@book.route('/add', methods=['GET', 'POST'])
def add_book():
    form = BookForm()
    authors = Authors.query.all()
    form.authors.choices = [(author.id, f'{author.name} {author.lastname}') for author in authors]
    if not authors:
        flash('Necesitas un autor minimo, agrega uno...', 'warning')
        return redirect(url_for('author.add_author'))
    context = {
        'title': "Agregar",
        'form': form
    }
    if form.validate_on_submit():
        book = Books(
            title=form.title.data,
            autor_id=form.authors.data,
            pub_date=form.pub_date.data
        )
        db.session.add(book)
        db.session.commit()
        flash('Libro registrado con éxito!', 'success')
        return redirect(url_for('book.list_books'))
    return render_template('book/form.html', **context)


@book.route('/edit/<int:book_id>', methods=['GET', 'POST'])
def edit_book(book_id):
    book = Books.query.get_or_404(book_id)
    form = BookForm(obj=book)
    authors = Authors.query.all()
    form.authors.choices = [(author.id, f'{author.name} {author.lastname}') for author in authors]
    context = {
        'title': "Editar",
        'form': form,
        'book': book
    }
    if form.validate_on_submit():
        book.title = form.title.data,
        book.autor_id = form.authors.data,
        book.pub_date = form.pub_date.data
        db.session.commit()
        flash('Libro editado con éxito!', 'success')
        return redirect(url_for('book.list_books'))
    return render_template('book/form.html', **context)


@book.route('/delete/<int:book_id>', methods=['GET', 'POST'])
def delete_book(book_id):
    book = Books.query.get_or_404(book_id)
    form = BookForm(obj=book)
    authors = Authors.query.all()
    form.authors.choices = [(author.id, f'{author.name} {author.lastname}') for author in authors]
    context = {
        'title': 'Eliminar',
        'form': form,
        'book': book
    }
    if form.validate_on_submit():
        db.session.delete(book)
        db.session.commit()
        flash('Libro Eliminado con éxito!', 'success')
        return redirect(url_for('book.list_books'))
    return render_template('book/form.html', **context)

app/templates/author/form.html
{% extends 'base.html' %}
{% block title %}
    {{ super() }}
    {{ title }} Autor
{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center mt-3">{{ title }} Autor</h1>
        {% if title == 'Eliminar'%}
            <div class="alert alert-danger" role="alert">
              Seguro que quieres eliminar al siguiente autor ?
            </div>
        {% endif %}
        <form action="
            {% if title == 'Agregar'%}
                {{ url_for('author.add_author') }}
            {% elif  title == 'Editar' %}
                {{ url_for('author.edit_author', author_id=author.id) }}
            {% else %}
                {{ url_for('author.delete_author', author_id=author.id) }}
            {% endif %}
            " method="POST">
            {{ form.csrf_token }}
            <div class="mb-3">
                {{ form.name.label(class="form-label") }}
                {% if title == 'Eliminar'%}
                    {{ form.name(class="form-control", readonly=True) }}
                {% else %}
                    {{ form.name(class="form-control") }}
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.lastname.label(class="form-label") }}
                {% if title == 'Eliminar'%}
                    {{ form.lastname(class="form-control", readonly=True) }}
                {% else %}
                    {{ form.lastname(class="form-control") }}
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.email.label(class="form-label") }}
                {% if title == 'Eliminar'%}
                    {{ form.email(class="form-control", readonly=True) }}
                {% else %}
                    {{ form.email(class="form-control") }}
                {% endif %}
            </div>
            <div class="text-center">
                {{ form.submit(class="btn btn-info mx-3") }}
            <a class="btn btn-danger" href="{{ url_for('author.list_authors') }}">Cancelar</a>
            </div>
        </form>
    </div>
{% endblock %}
{% block javascript %}
<script>
$( ".nav-author" ).addClass( "active");
</script>
{% endblock %}

app/templates/author/list.html
{% extends 'base.html' %}
{% block title %}
    {{ super() }}
    Autores
{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center mt-3">Lista de Autores</h1>
        <a class="btn bg-info" href="{{ url_for('author.add_author') }}">Agregar</a>
        {% if authors %}
        <table class="table table-striped mt-3">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Nombre</th>
              <th scope="col">Apellidos</th>
              <th scope="col">Correo</th>
              <th scope="col">Libros Relacionados</th>
              <th scope="col">Acciones</th>
            </tr>
          </thead>
          <tbody>
          {% for author in authors %}
              <tr>
                  <th scope="row">{{ author.id }}</th>
                  <td>{{ author.name }}</td>
                  <td>{{ author.lastname }}</td>
                  <td>{{ author.email }}</td>
                  <td>{% if author.book %}
                        {{ author.book | join(', ')}}
                        {% else %}
                          Ningun Libro
                    {% endif %}
                  </td>
                  <td>
                      <a href="{{url_for('author.edit_author', author_id=author.id) }}" class="btn btn-info">Editar</a>
                      <a href="{{url_for('author.delete_author', author_id=author.id) }}" class="btn btn-danger">Eliminar</a>
                  </td>
            </tr>
            <tr>
          {% endfor %}
          </tbody>
        </table>
        {% else %}
            <div class="alert alert-warning mt-3" role="alert">
              No tienes a ningun autor registrado aun...
            </div>
        {% endif %}
    </div>
{% endblock %}
{% block javascript %}
<script>
$( ".nav-author" ).addClass( "active");
</script>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %} Biblioteca |{% endblock %}
    </title>
<link rel="icon" href="{{ url_for('static',filename='images/logo.png') }}">
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
 <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
<body>
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{% for message  in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ message[0]}} alert-dismissible m-4" role="alert">
        {{ message[1] }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}
{% block body %}
{% endblock %}
{% block javascript %}
{% endblock %}
</body>
</html>

app/templates/book/form.html
{% extends 'base.html' %}
{% block title %}
    {{ super() }}
    {{ title }} Libro
{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center mt-3">{{ title }} Libro</h1>
        {% if title == 'Eliminar'%}
            <div class="alert alert-danger" role="alert">
              Seguro que quieres eliminar al siguiente Libro ?
            </div>
        {% endif %}
        <form action="
            {% if title == 'Agregar'%}
                {{ url_for('book.add_book') }}
            {% elif  title == 'Editar' %}
                {{ url_for('book.edit_book', book_id=book.id) }}
            {% else %}
                {{ url_for('book.delete_book', book_id=book.id) }}
            {% endif %}
            " method="POST">
            {{ form.csrf_token }}
            <div class="mb-3">
                {{ form.title.label(class="form-label") }}
                {% if title == 'Eliminar'%}
                    {{ form.title(class="form-control", readonly=True) }}
                {% else %}
                    {{ form.title(class="form-control") }}
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.pub_date.label(class="form-label") }}
                {% if title == 'Eliminar'%}
                    {{ form.pub_date(class="form-control", readonly=True) }}
                {% else %}
                    {{ form.pub_date(class="form-control") }}
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.authors.label(class="form-label") }}
                {% if title == 'Eliminar'%}
                    {{ form.authors(class="form-control", readonly=True) }}
                {% else %}
                    {{ form.authors(class="form-control") }}
                {% endif %}
            </div>
            <div class="text-center">
                {{ form.submit(class="btn btn-info mx-3") }}
            <a class="btn btn-danger" href="{{ url_for('book.list_books') }}">Cancelar</a>
            </div>
        </form>
    </div>
{% endblock %}
{% block javascript %}
<script>
$( ".nav-book" ).addClass( "active");
</script>
{% endblock %}

app/templates/book/list.html
{% extends 'base.html' %}
{% block title %}
    {{ super() }}
    Libros
{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center mt-3">Lista de Libros</h1>
        <a class="btn bg-info" href="{{ url_for('book.add_book') }}">Agregar</a>
        {% if books %}
        <table class="table table-striped mt-3">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Titulo</th>
              <th scope="col">Autor</th>
              <th scope="col">Fecha de Publicacion</th>
              <th scope="col">Acciones</th>
            </tr>
          </thead>
          <tbody>
          {% for book in books %}
              <tr>
                  <th scope="row">{{ book.id }}</th>
                  <td>{{ book.title }}</td>
                  <td>{{ book.author }}</td>
                  <td>{{ book.pub_date }}</td>
                  <td>
                      <a href="{{url_for('book.edit_book', book_id=book.id) }}" class="btn btn-info">Editar</a>
                      <a href="{{url_for('book.delete_book', book_id=book.id) }}" class="btn btn-danger">Eliminar</a>
                  </td>
            </tr>
            <tr>
          {% endfor %}
          </tbody>
        </table>
        {% else %}
            <div class="alert alert-warning mt-3" role="alert">
              No tienes a ningun libro registrado aun...
            </div>
        {% endif %}
    </div>
{% endblock %}
{% block javascript %}
<script>
$( ".nav-book" ).addClass( "active");
</script>
{% endblock %}

app/templates/hello.html
{% extends 'base.html' %}
{% import 'macros.html' as macros %}
{% block title %}
    {{ super() }}
    Bienvenido
{% endblock %}

{% block body %}
    {% if username %}
        <h1>Bienvenido, {{ username | capitalize }}</h1>
    {% endif %}
    {% if user_ip %}
        <h3>Tu Ip es {{ user_ip }}</h3>
    {% else %}
    <a href="{{ url_for('index') }}">Ir a inicio</a>
    {% endif %}
    <p>Lista de Todos</p>
    <ul>
        {% for todo in todos %}
            {{ macros.render_todo(todo) }}
        {% endfor %}
    </ul>
{% endblock %}

app/templates/library.html
{% extends 'base.html' %}
{% block title %}
    {{ super() }}
    Inicio
{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center m-2">Biblioteca</h1>
    <h4>Proyecto hecho en Flask :)</h4>
    </div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% block title %}
    {{ super() }}
    Login
{% endblock %}

{% block body %}
    <div class="container">
        <form action="{{ url_for('auth.login') }}" method="POST">
            {{ login_form.csrf_token }}
            <div class="mb-3">
                {{ login_form.username.label(class="form-label") }}
                {{ login_form.username(class="form-control") }}
          </div>
          <div class="mb-3">
                {{ login_form.password.label(class="form-label") }}
                {{ login_form.password(class="form-control") }}
          </div>
          {{ login_form.submit(class="btn btn-info") }}
        </form>
    </div>
{% endblock %}

app/templates/macros.html
{% macro render_todo(todo) %}
    <li>{{ todo }}</li>
{% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('index') }}">
        <img src="{{ url_for('static',filename='images/logo.png') }}" alt="biblioteca logo" width="30" height="30 ">
        Biblioteca</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link nav-book" href="{{ url_for('book.list_books') }}">Libros</a>
        <a class="nav-link nav-author" href="{{ url_for('author.list_authors') }}">Autores</a>
      </div>
    </div>
  </div>
</nav>